#! /bin/sh

### BEGIN INIT INFO
# Provides:		st-dns
# Required-Start:	$all
# Required-Stop:	$all
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description: smart dns server, support UDP/DOT/TCP
### END INIT INFO
set -e
case "$1" in
  start)
        nohup /usr/local/bin/st-dns > /tmp/st-dns.log 2>/tmp/st-dns.error &
        ;;
  stop)
        pid=`cat /var/run/st-dns.pid`
        if [ "$pid" != "" ];then
            kill -9 `cat /var/run/st-dns.pid`
        fi
        rm -rf /var/run/st-dns.pid
        ;;
  restart)
        pid=`cat /var/run/st-dns.pid`
        if [ "$pid" != "" ];then
            kill -9 `cat /var/run/st-dns.pid`
        fi
        rm -rf /var/run/st-dns.pid
        nohup /usr/local/bin/st-dns > /tmp/st-dns.log 2>/tmp/st-dns.error &
        ;;
  *)
        echo "Usage: st-dns <start|stop|restart>"
esac

exit 0