#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

USE_PROCD=1
START=18
start_service() {
    procd_open_instance
    procd_set_param command  /usr/sbin/st-dns -c /etc/st/dns
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 60 1 500000
    procd_set_param limits core="unlimited"
    procd_close_instance
}